<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>SOPRA BANKING MAIL</title>
</head>

<body>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td align="center" valign="top" bgcolor="#838383"
				style="background-color: #838383;"><br> <br>
				<table width="600" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<td align="center" valign="top" bgcolor="#d3be6c"
							style="background-color: #d3be6c; font-family: Arial, Helvetica, sans-serif; font-size: 13px; color: #000000; padding: 0px 15px 10px 15px;">

							<div style="font-size: 48px; color:blue;">
								<b>Java Techie</b>
							</div>

							<div style="font-size: 24px; color: #555100;">
								<br> Sending Email using Spring Boot with <b>FreeMarker
									template !!! <br>
							</div>
							<div>
                                    <br>  Lorem ipsum dolor sit amet, consectetur adipisci elit,
                                            sed eiusmod tempor incidunt ut labore et dolore magna aliqua.
                                            Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis
                                            suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis
                                            aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat
                                            nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt
                                             in culpa qui officia deserunt mollit anim id est laborum.
                                    <br>
								<br>"THIS IS FROM SOPRABANKING. PLEASE FOLLOW THE COMMANDS" <br> <br>
								<br>
							</div>
						</td>
					</tr>
				</table> <br> <br></td>
		</tr>
	</table>
</body>
</html>